// <auto-generated />
using System;
using Apolon.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Apolon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Apolon.Data.Models.Card", b =>
                {
                    b.Property<Guid>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the card");

                    b.Property<int>("CardType")
                        .HasColumnType("integer")
                        .HasComment("Type of membership/subscription card");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the card");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key referencing the associated user");

                    b.HasKey("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Apolon.Data.Models.Split", b =>
                {
                    b.Property<Guid>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the workout split");

                    b.Property<string>("SplitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of the workout split (e.g., Push/Pull/Legs, Upper/Lower)");

                    b.PrimitiveCollection<int[]>("TargetedMuscles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasComment("List of targeted muscle groups included in this split");

                    b.HasKey("SplitId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("Apolon.Data.Models.Supplement", b =>
                {
                    b.Property<Guid>("SupplementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the supplement");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key referencing the supplement brand");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key referencing the supplement category");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Description detailing the supplement's ingredients and usage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of the supplement");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the supplement");

                    b.HasKey("SupplementId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Supplements");
                });

            modelBuilder.Entity("Apolon.Data.Models.SupplementBrand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the supplement brand");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of the supplement brand");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Description of the brand and its products");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Contact email of the brand");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Contact phone number of the brand");

                    b.HasKey("BrandId");

                    b.ToTable("SupplementsBrands");
                });

            modelBuilder.Entity("Apolon.Data.Models.SupplementCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the supplement category");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("The category type (e.g., Protein, Creatine, Pre-Workout)");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Description detailing the category and its intended benefits");

                    b.HasKey("CategoryId");

                    b.ToTable("SupplementsCategories");
                });

            modelBuilder.Entity("Apolon.Data.Models.Trainer", b =>
                {
                    b.Property<Guid>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Description for the trainer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Email of the trainer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("First name of the trainer");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasComment("Trainer sex");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The Image Of The Trainer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Last name of the trainer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Phone number of the trainer");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Most muscular man in history!",
                            Email = "vezenkov07@gmail.com",
                            FirstName = "Luboslav",
                            Gender = 'M',
                            ImageUrl = "/images/trainers/me.jpg",
                            LastName = "Vezenkov",
                            PhoneNumber = "+359888747824"
                        },
                        new
                        {
                            TrainerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "The best dog in the world. Can teach you how to hunt cats.",
                            Email = "ornelamuti@gmail.com",
                            FirstName = "Ornela",
                            Gender = 'F',
                            ImageUrl = "/images/trainers/ornela.jpg",
                            LastName = "Muti",
                            PhoneNumber = "+3596969696969"
                        });
                });

            modelBuilder.Entity("Apolon.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the user");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date of birth of the user");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("First name of the user");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasComment("Height of the user in centimeters");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Last name of the user");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasComment("Weight of the user in kilograms");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Apolon.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the workout session");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("End date and time of the workout session");

                    b.Property<Guid>("SplitId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key referencing the workout split");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Start date and time of the workout session");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid")
                        .HasComment("Optional foreign key referencing an assigned trainer");

                    b.HasKey("WorkoutId");

                    b.HasIndex("SplitId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Apolon.Data.Models.Card", b =>
                {
                    b.HasOne("Apolon.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Apolon.Data.Models.Supplement", b =>
                {
                    b.HasOne("Apolon.Data.Models.SupplementBrand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apolon.Data.Models.SupplementCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Apolon.Data.Models.Workout", b =>
                {
                    b.HasOne("Apolon.Data.Models.Split", "Split")
                        .WithMany()
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apolon.Data.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId");

                    b.Navigation("Split");

                    b.Navigation("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
